config/routes.rb
Rails.application.routes.draw do

resources :body_types
resources :bodies
root 'body_types#index'

end

app/models/body.rb
class Body < ActiveRecord::Base
belongs_to :body_type

def diamater_in_kms
relative_diameter * 12742


end
end

app/models/body_type.rb
class BodyType < ActiveRecord::Base
has_many :bodies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController

def show
@body = Body.find(params[:id])
end
end

app/controllers/body_types_controller.rb
class BodyTypesController < ApplicationController

def index
@body_types = BodyType.order('name ASC')
end

def show
@body_type = BodyType.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/helpers/body_types_helper.rb
module BodyTypesHelper
end

app/views/bodies/show.html.erb
<h1><%= body.name %></h1>

<p>
This is a 
<%= @body.body_type.name %>
</p>

<p>It is the <%body.position_from_sun %> rock from the sun.

<p> Diameter: <%= @body.diameter_in_kms_ %></p>
<p><%= link_to 'Home', root_path %></p>

app/views/body_types/index.html.erb
<h1> What have we got here? </h1>

<p> We have <%= @body_types.count %> body types!</p>

<% @body_types.each do |body_type| %>

<p>We have a <%= link_to(body_type.name, body_type_path(body_type)) %>
</p>

<% end %>

app/views/body_types/show.html.erb
<h1><%= @body_type.name %></h1>

<% @body_type.bodies.each do |body| %>
<p><%= link_to(body.name, body_path(body)) %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Solarsystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>